name: Release

# Controls when the action will run.
on:
  workflow_call:

{% import '.github/workflows/ci-cd.yml' as ci with context %}{# Use some Jinja macros -#}

jobs:
  # make a new version first, release or prerelease
  release:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      {{ ci.checkout(depth=0) }}

      - name: Setup git user
        shell: sh
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      {{ ci.setup_python() }}

      {{ ci.pip_install_req() }}

      - name: Update files with new version number
        env:
          GH_TOKEN: {{'${{secrets.GITHUB_TOKEN}}'}}
          PYTHONPATH: ci
        shell: sh
        run: |
          # update files not covered by semantic-release
          python ci/fixver.py $(semantic-release version --print)
          # run semantic-release in source tree only
          semantic-release version
          git status
